In [3]:
pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [7]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np

In [3]:
features = pd.read_csv(r"X_train_filtered.csv")
df_labels = pd.read_csv(r"y_train.csv")

labels = df_labels['topic']
print(type(labels))

<class 'pandas.core.series.Series'>


In [4]:
X_test = pd.read_csv(r"X_test_filtered.csv")
y_test = pd.read_csv(r"y_test.csv")

In [5]:
X_test_origin = pd.read_csv(r"X_test_origin.csv")
print(X_test_origin)
print(X_test_origin.shape)

                                                  text
0    Rovers reject third Ferguson bid\n\nBlackburn ...
1    Lufthansa flies back to profit\n\nGerman airli...
2    Holmes urged to compete at Worlds\n\nJolanda C...
3    US to rule on Yukos refuge call\n\nYukos has s...
4    Asylum children to face returns\n\nThe UK gove...
..                                                 ...
421  Irish finish with home game\n\nRepublic of Ire...
422  MG Rover China tie-up 'delayed'\n\nMG Rover's ...
423  Parmalat bank barred from suing\n\nBank of Ame...
424  Salary scandal in Cameroon\n\nCameroon says wi...
425  Federer breezes into semi-finals\n\nRoger Fede...

[426 rows x 1 columns]
(426, 1)


-Before we apply our training set to the model, first we need to split this training set to 2 more sets of training and test which are X_train and X_val.

-After that, we will apply those 2 sets to our model:

+Random Forrest

+SVC

-After training the 2 models, we will take the very first test set which we already had after cleaning the data to test our 2 models and we will also calculate 4 types of score: accuracy, precision, recall and f1 for each of the model.

-For each of the model, we also print the text and the prediction to that corresponding text.

-Finally, we will draw the confusion matrix of both models so that we can see how the 2 models predicted.

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(features, labels, train_size=0.8, random_state=42)

print(X_train.shape)
print(X_val.shape)

(1360, 2437)
(341, 2437)


In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# Train the model
model_forrest = RandomForestClassifier(
    # n_estimators=100,            # Number of trees in the forest (start with 200)
    # max_depth=10,                # Limit depth of the trees to reduce overfitting
    # min_samples_split=10,        # Minimum samples required to split a node
    # min_samples_leaf=5,          # Minimum samples required in a leaf node
    # max_features="sqrt",         # Use sqrt(number of features) for split
    # random_state=42,             # Ensure reproducibility
    # n_jobs=-1,                   # Use all CPU cores for training
    # class_weight="balanced"      # Handle class imbalance if present
)
model_forrest.fit(X_train, y_train)

y_pred_forrest = model_forrest.predict(X_val)

# Calculate 4 points: accuracy point, precision point, recall point and f1 point
accuracy = accuracy_score(y_val, y_pred_forrest)
precision = precision_score(y_val, y_pred_forrest, average="weighted")
recall = recall_score(y_val, y_pred_forrest, average="weighted")
f1 = f1_score(y_val, y_pred_forrest, average="weighted")

print(f"Accuracy score: {accuracy:.2f}")
print(f"Precision score: {precision:.2f}")
print(f"Recall score: {recall:.2f}")
print(f"F1 score: {f1:.2f}")

Accuracy score: 0.94
Precision score: 0.94
Recall score: 0.94
F1 score: 0.94


In [8]:
# Finally, apply the test set to the model

predictions = model_forrest.predict(X_test)

probabilities = model_forrest.predict_proba(X_test)

for i, text in enumerate(X_test_origin['text']):
    print(f"Text: {text}")
    print(f"Predicted Topic: {predictions[i]}")
    print(f"Prediction Probability: {probabilities[i]}")
    print("-------")

Text: Rovers reject third Ferguson bid

Blackburn have rejected a third bid from Rangers for Scotland captain Barry Ferguson, BBC Sport has learnt.

It is thought Blackburn want £6m for the midfielder but chief executive John Williams has confirmed the club are still "in dialogue" with Rangers. The 26-year-old has already handed in a transfer request at Ewood Park as he seeks a return to Ibrox. But the clubs have been unable to reach agreement over a fee for Ferguson, who moved to Lancashire in 2003 for £6.5m. On Thursday Rangers said they would not be increasing their offer of £4m.

Blackburn have said all along that they want £6m for the midfielder and Williams has rejected proposals from Rangers over a player-swap deal. Williams said: "We are in dialogue with Glasgow Rangers but we have no agreement." The negotiations will have to be concluded by midnight on Monday, when the winter transfer window shuts. Williams conceded any deal for Ferguson was looking "unlikely" before the c

In [9]:
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.pipeline import Pipeline

# Create a pipeline to scale features and train the SVM model
model_svm = Pipeline([
    ('scaler', StandardScaler()),  # Feature scaling
    ('svm', svm.SVC(C=100.0, kernel='linear', probability=True, class_weight='balanced'))  # Adjusted C and kernel
])

# Train the model
model_svm.fit(X_train, y_train)

# Predict on validation set
y_pred_svm = model_svm.predict(X_val)

# Calculate evaluation metrics
accuracy = accuracy_score(y_val, y_pred_svm)
precision = precision_score(y_val, y_pred_svm, average="weighted")
recall = recall_score(y_val, y_pred_svm, average="weighted")
f1 = f1_score(y_val, y_pred_svm, average="weighted")

# Print the scores
print(f"Accuracy score: {accuracy:.2f}")
print(f"Precision score: {precision:.2f}")
print(f"Recall score: {recall:.2f}")
print(f"F1 score: {f1:.2f}")

Accuracy score: 0.96
Precision score: 0.96
Recall score: 0.96
F1 score: 0.96


In [10]:
# Apply the test set to the SVC model

predictions = model_svm.predict(X_test)

probabilities = model_svm.predict_proba(X_test)

for i, text in enumerate(X_test_origin['text']):
    print(f"Text: {text}")
    print(f"Predicted Topic: {predictions[i]}")
    print(f"Prediction Probability: {probabilities[i]}")
    print("-------")

Text: Rovers reject third Ferguson bid

Blackburn have rejected a third bid from Rangers for Scotland captain Barry Ferguson, BBC Sport has learnt.

It is thought Blackburn want £6m for the midfielder but chief executive John Williams has confirmed the club are still "in dialogue" with Rangers. The 26-year-old has already handed in a transfer request at Ewood Park as he seeks a return to Ibrox. But the clubs have been unable to reach agreement over a fee for Ferguson, who moved to Lancashire in 2003 for £6.5m. On Thursday Rangers said they would not be increasing their offer of £4m.

Blackburn have said all along that they want £6m for the midfielder and Williams has rejected proposals from Rangers over a player-swap deal. Williams said: "We are in dialogue with Glasgow Rangers but we have no agreement." The negotiations will have to be concluded by midnight on Monday, when the winter transfer window shuts. Williams conceded any deal for Ferguson was looking "unlikely" before the c

In [11]:
from sklearn.metrics import confusion_matrix, classification_report

In [12]:
# Calculate and print the confusion matrix
print("Random Forrest: \n")

conf_matrix_forrest = confusion_matrix(y_val, y_pred_forrest)
print("Confusion Matrix:\n", conf_matrix_forrest)

# Print detailed classification report
class_report_forrest = classification_report(y_val, y_pred_forrest)
print("Classification Report:\n", class_report_forrest)


print("SVC: \n")

# Calculate and print the confusion matrix
conf_matrix_svc = confusion_matrix(y_val, y_pred_svm)
print("Confusion Matrix:\n", conf_matrix_svc)

# Print detailed classification report
class_report_svc = classification_report(y_val, y_pred_svm)
print("Classification Report:\n", class_report_svc)

Random Forrest: 

Confusion Matrix:
 [[75  0  2  2  1]
 [ 0 43  1  1  0]
 [ 1  0 68  1  2]
 [ 3  0  0 98  0]
 [ 2  1  1  1 38]]
Classification Report:
                precision    recall  f1-score   support

     business       0.93      0.94      0.93        80
entertainment       0.98      0.96      0.97        45
     politics       0.94      0.94      0.94        72
        sport       0.95      0.97      0.96       101
         tech       0.93      0.88      0.90        43

     accuracy                           0.94       341
    macro avg       0.95      0.94      0.94       341
 weighted avg       0.94      0.94      0.94       341

SVC: 

Confusion Matrix:
 [[78  0  2  0  0]
 [ 0 44  0  0  1]
 [ 2  2 68  0  0]
 [ 2  1  0 98  0]
 [ 1  3  0  0 39]]
Classification Report:
                precision    recall  f1-score   support

     business       0.94      0.97      0.96        80
entertainment       0.88      0.98      0.93        45
     politics       0.97      0.94      0.9